#pragma once

#define PERSON_SIZE 128
#define MAP_TILE_SCALE 2
#define PLAYER_SCALE 3
#define WIDTH_IN_TILES 20
#define HEIGHT_IN_TILES 16
#define WINDOW_WIDTH WIDTH_IN_TILES * 32 * MAP_TILE_SCALE
#define WINDOW_HEIGHT HEIGHT_IN_TILES * 32 *MAP_TILE_SCALE

#define PLAY_WIDTH WINDOW_WIDTH - 32 * MAP_TILE_SCALE * 2
#define PLAY_HEIGHT WINDOW_HEIGHT - 32 * MAP_TILE_SCALE * 2
//#define WINDOW_WIDTH 1200
//#define WINDOW_HEIGHT 900

